language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  local-dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master